### ISSUE TITLE
Error: expected buffer, found string

### ISSUE THREAD

**Issue by christianbundy** [flumedb/flumeview-hashtable#2]
I swear I wasn't doing anything weird. Anything I can include to help debug this? I think the view destroyed itself when it hit the error.

```
Error: expected buffer, found string
    at /home/christianbundy/src/ssbc/patchwork/node_modules/flumeview-hashtable/index.js:39:43
    at /home/christianbundy/src/ssbc/patchwork/node_modules/atomic-file/inject.js:46:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by christianbundy** [comment]
Another one: https://github.com/ssbc/patchwork/issues/972#issuecomment-482161840

**Comment by lpar** [comment]
Restarting Patchwork gave me the same error again with the `ipv4` branch, but going back to master, running unsuccessfully and restarting, it all came back to life.

**Comment by christianbundy** [comment]
I wonder whether this just occurs when you're quickly starting and killing Patchwork for testing? I'm not sure. I have a sample I can upload if that makes debugging helpful, but admittedly I haven't looked into which data is actually in there.

I tried restarting Patchwork a few times but it kept throwing the same error, so I resolved it with:

```sh
rm -f /home/christianbundy/.ssb/flume/keys.ht
```

**Comment by christianbundy** [comment]
I think this explains what was happening:

```console
$ npm ls atomic-file
ssb-patchwork@3.12.0-dev /home/christianbundy/src/ssbc/patchwork
├─┬ flumeview-reduce@1.3.16
│ └── atomic-file@2.0.0 
├─┬ ssb-gossip@1.0.6
│ └── atomic-file@1.1.5 
└─┬ ssb-server@14.1.9
  ├── atomic-file@1.1.5  extraneous
  └─┬ ssb-db@19.1.0
    └─┬ flumeview-hashtable@1.0.4
      └── UNMET DEPENDENCY atomic-file@^1.1.3
```

I think maybe I hadn't run `npm install` or something so flumeview-hashtable was using atomic-file@2.0.0 rather than 1.1.5. This caused problems because of [this commit](https://github.com/flumedb/atomic-file/commit/d7ec139953c511864affb7b10b9b6d37c32bab7d), but I don't think that there was actually any low-level problem.

**Comment by christianbundy** [comment]
I think this problem is caused by human error, but I think we should probably rebuild or do *something* rather than just error and freeze.

**Comment by christianbundy** [comment]
Looks like this is an npm bug from running `npm dedupe` when one of the deps is shrinkwrapped. Closing.
